### ISSUE TITLE
Need advice for extending the theme/project

### ISSUE THREAD

**Issue by ekafyi** [johno/digital-garden#50]
I love the idea of this project and would like to create something—for example music-specific frontmatter (`artist`, `track`, `album`) for `music` files and modify the components accordingly; or a "Reading List" for books.

Would you recommend forking and modifying `gatsby-theme-digital-garden`, OR creating a child theme, OR creating a whole new theme following the same structure as this one? Even if it's not a child theme, I'd be able to use it together with `gatsby-theme-digital-garden` thanks to theme composition, I presume? I’m still wrapping my head around how themes work in the real world.

Would appreciate your thoughts!

**Comment by johno** [comment]
For sure! That sounds way rad.

Really any of those approaches would work great! Digital Garden itself is pretty experimental and is being used to test out patterns, like [latent component shadowing](https://johno.com/latent-component-shadowing), so there's a decent amount of churn (which is now stabilizing).

Ideally, the preferred approach for adding new functionality/extending would be building child themes on top of `gatsby-theme-digital-garden`.  Though, right now we have some core work necessary to allow multiple instances of `gatsby-plugin-mdx` to run together (so that won't exactly work well until we can prioritize fixing that). This is why we allow an option to [opt out of MDX config](https://github.com/johno/digital-garden/blob/16e4f400eb13684fca11ddd5f327b5a6dac59b4c/packages/gatsby-theme-digital-garden/gatsby-config.js#L4).

Considering we'd also like to support music and reading lists in digital-garden I could add you as a collaborator (if you're interested) so you could start building those two themes similarly to `gatsby-theme-digital-garden-blog` and `gatsby-theme-digital-garden-portfolio` into Digital Garden core.

Hopefully this helps answer some of your questions. Please let me know if something's unclear!

**Comment by ekafyi** [comment]
Thanks for your response, John!

Sure, I would love to contribute, that would be great!

Some questions though related to theme composition:

> we have some core work necessary to allow multiple instances of gatsby-plugin-mdx to run together

Would this affect other themes that also source from `gatsby-plugin-mdx`? ie. Can a user use both `gatsby-theme-digital-garden` and a different theme that also uses that plugin together? Would the options for the plugin be composed together, or would they have to opt out of MDX config like you mentioned?

Secondly, I've looked at the themes and I'm still not clear about the relations—are `gatsby-theme-digital-garden-blog` and `gatsby-theme-digital-garden-portfolio` child themes of `gatsby-theme-digital-garden`? What would indicate child-parent theme relation? (From this repo https://github.com/jlengstorf/livestream-gatsby-themes/tree/master/packages, I can see `gatsby-theme-child` is a child of `gatsby-theme-livestream` because it has the latter in its dependencies.)

**Comment by johno** [comment]
> Sure, I would love to contribute, that would be great!

I've added you as a collaborator 😸 

> Would this affect other themes that also source from gatsby-plugin-mdx? ie. Can a user use both gatsby-theme-digital-garden and a different theme that also uses that plugin together? Would the options for the plugin be composed together, or would they have to opt out of MDX config like you mentioned?

It would. Currently they need to opt out (unfortunately). It's definitely a limitation in the core APIs of Gatsby that we will be addressing sometime soon so that it won't be necessary in the future.

> Secondly, I've looked at the themes and I'm still not clear about the relations—are gatsby-theme-digital-garden-blog and gatsby-theme-digital-garden-portfolio child themes of gatsby-theme-digital-garden?

I guess I'd call them "sibling" themes. Though, right now blog/portfolio are dependent upon `gatsby-theme-digital-garden` as a result of the `gatsby-plugin-mdx` issue above. Once that's resolved it's intended that users can "mix in" any aspect of Digital Garden. Sort of like lego blocks of common website functionality that isn't dependent on anything else.

This'd allow a user to have a theme composition like:

```js
  [
    'some-other-blog-theme',
    'some-other-notes-theme',
    'gatsby-theme-digital-garden-music',
    'gatsby-theme-digital-garden-portfolio'
]
```

> What would indicate child-parent theme relation?

A child theme relation is indicated by it existing in the `gatsby-config.js` under `__experimentalThemes`. `gatsby-theme-child` is the child because it [configures `gatsby-theme-livestream`](https://github.com/jlengstorf/livestream-gatsby-themes/blob/aa787d6cbc53352e5e0c4ddb05c64575f04ff303/packages/gatsby-theme-child/gatsby-config.js#L2). `gatsby-theme-livestream` is the parent because the child is dependent upon it.

**Comment by ekafyi** [comment]
Thanks! Forked it and going to play around with it now.
