### ISSUE TITLE
RFC: Migrate to GitHub Actions

### ISSUE THREAD

**Issue by johnletey** [johno/digital-garden#57]
I see that @adrw added CircleCI in #54, but I was thinking that we should start using GitHub Actions! What are your guys' thoughts?

cc @johno @ChristopherBiscardi

**Comment by adrw** [comment]
I don't have any experience in GitHub Actions and am not sure what purpose it would serve. It seems to be for more complex CI workflows.

**Comment by johno** [comment]
Yeah, for now I think CircleCI works since their error logging and such is more robust. I do think we could concoct an action to automatically publish starters to standalone repos though: https://github.com/johno/actions-push-subdirectories

Thought being we can move the different starters (site/site-dark) to an `examples` repo and automatically push to johno/gatsby-starter-digital-garden and johno/gatsby-starter-digital-garden-dark.

Might even make sense to make an org like `digital-gardens` now that I think about it.

**Comment by adrw** [comment]
I like that idea, starters as their own repo would make it easier for people to clone and get started. An org would help organize all the related repos 👍

Thoughts on adding Renovate bot? I've been finding it helpful in other web repos to keep dependencies from going too stale.

**Comment by johno** [comment]
> Thoughts on adding Renovate bot? I've been finding it helpful in other web repos to keep dependencies from going too stale.

Sure! 👍

**Comment by adrw** [comment]
@johno Can you add Renovate bot [here](https://github.com/apps/renovate)? I'll add the configuration file in a follow up PR.

**Comment by johnletey** [comment]
@johno I like your idea of making a digital garden organization and a separate repo with all of the starters!

> Yeah, for now I think CircleCI works since their error logging and sush is more robust.

Sounds good ... should I close this then?

**Comment by adrw** [comment]
@johnletey To clarify, I think the idea was a unique repo for each starter so that new people could simply clone or fork that repo instead of having to parse out what files they could delete out of a monorepo / copying files manually.

**Comment by johnletey** [comment]
Yes @adrw ... that's what I had in mind when I read John's comment

**Comment by johno** [comment]
We're now using GitHub Actions for all the things : )
